# Generated by Django 4.0.6 on 2022-08-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_shopping_cart_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
