# Generated by Django 4.0.6 on 2022-09-02 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_discount_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dsc',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='discountOf', to='model.discount'),
        ),
    ]
