# Generated by Django 4.0.6 on 2022-09-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0009_alter_product_dsc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='dsc',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discountOf', to='model.discount'),
        ),
    ]
