# Generated by Django 4.0.6 on 2022-09-07 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0011_alter_shopping_cart_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_purchases',
            field=models.IntegerField(default=0),
        ),
    ]
