# Generated by Django 4.0.6 on 2022-08-13 00:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('model', '0002_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopping_cart',
            name='product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_nameOf', to='model.test'),
        ),
        migrations.AlterField(
            model_name='shopping_cart',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usernameOf', to=settings.AUTH_USER_MODEL),
        ),
    ]
