# Generated by Django 4.0.6 on 2022-09-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_product_number_of_purchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Details',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
