# Generated by Django 4.0.6 on 2022-07-27 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id_age',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
