# Generated by Django 4.0.6 on 2022-07-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_person_id_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='person',
        ),
    ]
